add auth workload identify federation

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -30,17 +30,22 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-node-
 
-      - name: Check for Service Account Key
-        run: |
-          if [ -z "${{ secrets.SERVICE_ACCOUNT_KEY }}" ]; then
-            echo "Missing SERVICE_ACCOUNT_KEY secret"
-            exit 1
-          fi
+      # - name: Check for Service Account Key
+      #   run: |
+      #     if [ -z "${{ secrets.SERVICE_ACCOUNT_KEY }}" ]; then
+      #       echo "Missing SERVICE_ACCOUNT_KEY secret"
+      #       exit 1
+      #     fi
 
       - id: 'auth'
         uses: 'google-github-actions/auth@v2'
         with:
-          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
+          # credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'
+          # workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
+          # service_account: '${{ secrets.SERVICE_ACCOUNT_EMAIL }}'
+          project_id: 'learngcp-418900'
+          workload_identity_provider: 'projects/993297422782/locations/global/workloadIdentityPools/github/providers/my-repo'
+          # service_account: 'storage-admin-bhuy@learngcp-418900.iam.gserviceaccount.com'
 
       - name: 'Set up Cloud SDK'
         uses: 'google-github-actions/setup-gcloud@v2'
@@ -63,8 +68,12 @@ jobs:
           echo "Cleaning up after deployment"
           # Add any cleanup commands here if necessary
 
-      - name: Notify on Failure
-        if: failure()
-        run: |
-          echo "Deployment failed. Notifying the team."
-          # Add notification commands here (e.g., send a message to Slack)
+      # - name: Notify Slack on failure
+      # if: failure()
+      # uses: 8398a7/action-slack@v3
+      # with:
+      #   status: ${{ job.status }}
+      #   fields: job,repo,commit,author,action,eventName,ref,workflow,took
+      #   webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
+      # env:
+      #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
